---
-
  loop:
    - mysql-server
    - php-mysqlnd
    - python3-PyMySQL
  name: "Install MySQL Packages"
  yum: "name={{ item }} update_cache=yes state=latest"
-
  name: "Start mysqld service"
  systemd: "name=mysqld state=started enabled=yes"
-
  mysql_user:
    login_host: localhost
    login_password: ""
    login_user: root
    name: root
    password: "{{ mysql_root_password }}"
    state: present
  name: "Set MySQL root Password"
-
  mysql_db:
    login_password: "{{ mysql_root_password }}"
    login_user: root
    name: "{{ mysql_db }}"
    state: present
  name: "Creates database for WordPress"
-
  mysql_user:
    login_password: "{{ mysql_root_password }}"
    login_user: root
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
  name: "Create MySQL user for WordPress"
