---
-
  ansible.builtin.rpm_key:
    key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
    state: present
  name: "Import Remi Key"
-
  name: "Install PHP Remi Repository"
  yum: "name=http://rpms.remirepo.net/enterprise/remi-release-8.rpm update_cache=yes state=latest"
-
  command: "dnf module enable php:remi-7.4 -y"
  name: "Enable PHP Remi Repository"
-
  loop: "{{ php_modules }}"
  name: "Install PHP Extensions"
  yum: "name={{ item }} update_cache=yes state=latest"
